server.port=7777
#debug=true

# file upload
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

#mysql
spring.datasource.url=jdbc:mysql://localhost:3306/mall?useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
spring.datasource.username=root
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=123456
spring.data.redis.timeout=5000ms
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0

# email
spring.mail.host=smtp.qq.com
spring.mail.port=587
spring.mail.username=1359838304@qq.com
spring.mail.password=burhldepwtbvbage
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# mybaits
mybatis.mapper-locations=classpath:mapper/*.xml,classpath*:com/example/**/mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# deepseek
spring.ai.deepseek.api-key=sk-e76323917504450fbe76f1b4297bf164

# alibailian
spring.ai.dashscope.api-key=sk-91c01cb247034c85a85cdf26ccd83204
spring.ai.dashscope.embedding.enabled=true
spring.ai.dashscope.embedding.options.model=text-embedding-v4

# vector database Qdrant
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=vector_store
spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.rest-port=6333
qdrant.vector-size=1536
qdrant.distance=Cosine

# alipay
alipay.app-id=9021000162698884
alipay.private-key=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCfyzDEDE/Knp+imUngTcZPSR3b/xmZFlGspO4LE/FXky9kTiY95DPiQ3Xf1nPFtLTfIERtnK5Jl0+/4DYIA1hvR/rWKdE40Ty9PdrvP65tdn1FLLG3Xe/gWmlALK0+8W6pNUfDk9wyS9qwL0rm5gqloGQ3i79J8nnqm28mxsouepZjnXIpzSTzS8OIJAsWWauHCxE4EAHn1xx4RjIWBIuvj+zUHQ+4PVCqhCg7PHXKgTAP+vXB4LqJ/c2TwghT4ZdNGvixxFWE1mxgUGtYyD64FQSwJ0lN6/MVUl+VzCVrTdDpNDkVNcz61Ou6ziAACNURIa/HxNvi3fuQ9wrzj3erAgMBAAECggEAaUUsSEuwGVUs56rCz6GNPth1cmR50a+xeOJi7CtkOIR/mT4e1XFMeQhmVGNse9gTvFb+nZO2AkdLw6WLEvZZQV6TMpnz+tFliWqBnFJAsF56IqNSJPIewJfvdNa5/5iAhbrTH1Z+nyf311AgsULlyr2CqFFJYQb8KIHj1RDrS3huCnlBcVnqdH8+5iPcE+CUK4QrA6DeNWoPCo05fBn234x928KY7XgDfw5YHUE/i0YjHW86IUzYUeGZK/eFR1DEaMmDoSKBZPyUIT9sAOxKomqNbwXNW4i9zC4cEefRaKyqoaovq21+mwawDPOTkEFio96uWiKe5YBODJ8/0VlR0QKBgQDY/4MkCQ+ytHmxk3O3AIrYau+qtsp/g0/hQpf1dqwliDUHAAAIJocZiUAvqTvIgArq9OTJ90mgpPYLxzjjR0IJfZNBbxqK6t6TV//l/VlOZFeWEeTe9Hit7eZfuxOzB9kV/vt+fk7zcNMYSiMFMaZvXx/fKILOzlzEQ+TQDvkpWQKBgQC8g5kFoEQ6Rpb+XOkYRv50c/XXOSdITpmS8t32RMiYMEPFVxKJVTDw/0FzMp7wRxQGLJUFN7/2bUaK7ONbwq2Pi3AXQLq/CUk7w2NvID6onP7+b/Gep/1tmT4LoUcNS8SLHEjECwuHUEh5SU+/gEJrvGApWyRHlBLcinM81xLEowKBgBS8vlSYRRbH5oVQ2RMZCyvJdGP1Gf77loupaIo9sA/aJ28m0dn1jJ2lHywu2Ra9Hc38X0zpw/CFMzpG7KnTqnzrskHjkz7JWUHte/gHsRwrvK8LwLqJ1GqSvJxTbXuDeXx/pJsfCP58vr+ofhZF+2jTR2F1JqMK15SuBFTZyXfpAoGAOStjpbwj1NSBiCRfIFivZFuia6HOkvQbSOBUhhH4D4dbliZA3dszG3MdwzTP1KiJnxG4I7vzgGVFZm5OyQ4yGn08AiFEQRks12364sGRnwr1ne4PBYGGrs0xbs97P8IBmfp66tE6rs+fGwErqTTZb9jSBNi6GOcEDVQDfKjw7ScCgYEArdCf8Kr0XTg7zSRyLDsmWnk7NaUYh6VC5dt5k6/agguKdZQOlKT5FnE1rWMfMJxsfN3wvqxT8BBtkUpaOqj0V6FjM2qPcAUMZT4mDc1sbTfhfGRUMEsHPL3nn8RKX0aoVT0hYssf2Ain8N1r8mgm+7WpIl+uCUGdArfNylj1fXQ=
alipay.alipay-public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1qi/On+nsT59I/t7W8IdsNQPob+sHyWrmqBkKZwvBEOxNp2T5bWTJ4mlTA3MGfInohTOb9OBWytlUaW7pH6hKdA4ugcOCnk8VOxUu7IdcxGpA7GdPw0YsbMrwWqoHw8WX5R1kqE1q9vl4kJGO3LRqddX/7VisNUOtar8CLl8wdeIiEAvyOh/sEcO9D4BFX10RcDdY4qDhjj+hI9bMVz0P8RVtY2GKRs6nMcZ9IUmb5auQeZQhNR3fydp5v5oODs9ghdXr6Ek8gcirJL4Hx08OEKEqHA2oFGAvkmqVGJG4w/9mgrmi+VRLqDmQfCbBQrrnt1xK0IRdd1WgWbGjgjX8QIDAQAB
alipay.gateway=https://openapi-sandbox.dl.alipaydev.com/gateway.do
# alipay.notify-url=http://localhost:7777/alipay/notify
# alipay.return-url=http://localhost:5173/payment/result
alipay.notify-url=http://yf637828.natappfree.cc/alipay/notify
alipay.return-url=http://yf637828.natappfree.cc/payment/result
alipay.connect-timeout=30000
alipay.read-timeout=60000

# qq login
qq.frontend-url=http://localhost:5174
qq.redirect-uri=http://d592f2a6.natappfree.cc/qq/callback
qq.app-id=1903993948
qq.app-key=X1NaZKrJYZMuDoBK
qq.authorize-url=https://graph.qq.com/oauth2.0/authorize
qq.token-url=https://graph.qq.com/oauth2.0/token
qq.openid-url=https://graph.qq.com/oauth2.0/me
qq.user-info-url=https://graph.qq.com/user/get_user_info

# express kuaidi100
express.customer=51A9B3D4FEEF123E587F925D51B23902
express.key=YGjQoLYO9840
express.secret=214d5ae6fcc24742b33dbda17f749e7c
express.userid=e50ff33cf781404c8e8f42d036cee33f





